-- ============================================================================
-- MIGRATION 004: Multi-Agent Persistent Memory Schemas (State Layer)
-- Project Tender — Unified Memory & Aggregation Layer
-- Target: PostgreSQL 15+ with TimescaleDB 2.x
-- ============================================================================

-- ============================================================================
-- TABLE: agent_state_checkpoints
-- Unified memory layer for Temporal/LangGraph agent framework.
-- Stores episodic memory, procedural state, and serialized payloads
-- generated by Python workers executing fraud scoring workflows.
--
-- CHECKPOINT TYPES:
--   episodic:   Discrete event memories (e.g., "found anomaly in NHAI tender #123")
--               Used for: Agent recall, audit trail, pattern detection
--
--   procedural: Workflow state snapshots (e.g., "step 3 of IRI calculation")
--               Used for: Workflow resumption after crash, debugging
--
--   payload:    Serialized output (e.g., RTI dossier JSON, anomaly report)
--               Used for: Downstream consumption, UI display, archival
--
-- WHY JSONB:
-- Different agents produce different state shapes. JSONB provides schema
-- flexibility while maintaining query performance via GIN indexing.
-- The state column is indexed with jsonb_path_ops for fast key-path lookups.
--
-- TEMPORAL INTEGRATION:
-- workflow_id maps to Temporal's workflow execution ID.
-- activity_id maps to Temporal's activity execution ID.
-- This enables 1:1 mapping between agent memory and Temporal history.
-- ============================================================================

CREATE TABLE agent_state_checkpoints (
    checkpoint_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Temporal workflow identifiers
    workflow_id       TEXT NOT NULL,                    -- Temporal workflow execution ID
    workflow_run_id   TEXT,                             -- Temporal run ID (for retries)
    activity_id       TEXT,                             -- Temporal activity ID (if applicable)

    -- Agent identification
    agent_name        TEXT NOT NULL,                    -- e.g., 'iri_calculator', 'rti_generator', 'anomaly_detector'
    checkpoint_type   checkpoint_type_enum NOT NULL,    -- episodic | procedural | payload

    -- State payload (JSONB for flexible schema)
    state             JSONB NOT NULL,                   -- Agent state snapshot (structure varies by agent)

    -- Traceability: link to specific contract(s) if applicable
    contract_id       UUID REFERENCES aoc_clean(contract_id) ON DELETE SET NULL,
    org_id            UUID REFERENCES org_summary(org_id) ON DELETE SET NULL,
    vendor_id         UUID REFERENCES vendor_summary(vendor_id) ON DELETE SET NULL,

    -- Execution metadata
    execution_status  TEXT NOT NULL DEFAULT 'running',  -- running | completed | failed | cancelled
    error_message     TEXT,                             -- Error details if failed
    execution_duration_ms INTEGER,                      -- Execution time in milliseconds

    -- Temporal metadata
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at        TIMESTAMPTZ,                      -- Optional TTL for ephemeral checkpoints

    -- Constraints
    CONSTRAINT workflow_id_not_empty CHECK (workflow_id <> ''),
    CONSTRAINT agent_name_not_empty CHECK (agent_name <> '')
);

-- ============================================================================
-- INDEXES ON agent_state_checkpoints
-- ============================================================================

-- GIN index on state JSONB for fast key-path lookups
-- Uses jsonb_path_ops for efficient containment queries (@>, ?&, ?|)
-- Example: WHERE state @> '{"anomaly_type": "single_bid"}'
CREATE INDEX idx_checkpoint_state_gin
    ON agent_state_checkpoints USING gin (state jsonb_path_ops);

-- Composite index for checkpoint replay (most common query pattern)
-- Covers: "Get all checkpoints for workflow X, agent Y, ordered by time"
CREATE INDEX idx_checkpoint_workflow_agent_time
    ON agent_state_checkpoints (workflow_id, agent_name, created_at DESC);

-- Index for contract-level traceability
-- Covers: "Get all agent memory related to contract Z"
CREATE INDEX idx_checkpoint_contract
    ON agent_state_checkpoints (contract_id, created_at DESC)
    WHERE contract_id IS NOT NULL;

-- Index for org-level traceability
-- Covers: "Get all agent memory related to department W"
CREATE INDEX idx_checkpoint_org
    ON agent_state_checkpoints (org_id, created_at DESC)
    WHERE org_id IS NOT NULL;

-- Index for vendor-level traceability
-- Covers: "Get all agent memory related to vendor V"
CREATE INDEX idx_checkpoint_vendor
    ON agent_state_checkpoints (vendor_id, created_at DESC)
    WHERE vendor_id IS NOT NULL;

-- Partial index for failed checkpoints (error investigation)
CREATE INDEX idx_checkpoint_failed
    ON agent_state_checkpoints (created_at DESC)
    WHERE execution_status = 'failed';

-- Index for TTL cleanup (ephemeral checkpoints)
CREATE INDEX idx_checkpoint_expires
    ON agent_state_checkpoints (expires_at)
    WHERE expires_at IS NOT NULL;

COMMENT ON TABLE agent_state_checkpoints IS 'Unified memory layer for Temporal/LangGraph agents. Stores episodic, procedural, and payload checkpoints with JSONB state.';
COMMENT ON COLUMN agent_state_checkpoints.state IS 'Agent state snapshot. Structure varies by agent. Indexed with GIN for fast key-path lookups.';
COMMENT ON COLUMN agent_state_checkpoints.workflow_id IS 'Temporal workflow execution ID. Enables 1:1 mapping between agent memory and Temporal history.';

-- ============================================================================
-- TABLE: agent_rti_payloads
-- Specialized table for RTI (Right to Information) dossier payloads.
-- Separated from generic checkpoints for:
--   1. Direct querying by RTI officers (no JSONB parsing needed)
--   2. Legal audit trail (immutable record of generated dossiers)
--   3. FK constraints to contracts and organizations
--
-- This table stores the final output of the RTI generation workflow,
-- including the formatted dossier text, CPIO address, and metadata.
-- ============================================================================

CREATE TABLE agent_rti_payloads (
    payload_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Traceability
    contract_id       UUID NOT NULL REFERENCES aoc_clean(contract_id) ON DELETE RESTRICT,
    org_id            UUID NOT NULL REFERENCES org_summary(org_id) ON DELETE RESTRICT,
    vendor_id         UUID REFERENCES vendor_summary(vendor_id) ON DELETE SET NULL,

    -- RTI dossier content
    rti_text          TEXT NOT NULL,                    -- Formatted RTI application text
    cpio_address      TEXT NOT NULL,                    -- Central Public Information Officer address
    applicant_name    TEXT NOT NULL DEFAULT '[Your Name]',
    application_date  DATE NOT NULL DEFAULT CURRENT_DATE,

    -- Dossier metadata
    anomaly_type      TEXT NOT NULL,                    -- e.g., 'single_bid', 'rush_job', 'extreme_delay'
    anomaly_severity  TEXT NOT NULL,                    -- low | medium | high | critical
    hhi_at_generation NUMERIC(8, 2),                   -- HHI at time of dossier generation
    iri_at_generation NUMERIC(5, 2),                   -- IRI at time of dossier generation

    -- Temporal workflow reference
    workflow_id       TEXT NOT NULL,
    checkpoint_id     UUID REFERENCES agent_state_checkpoints(checkpoint_id) ON DELETE SET NULL,

    -- Status
    status            TEXT NOT NULL DEFAULT 'generated', -- generated | sent | acknowledged | disputed
    generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT rti_text_not_empty CHECK (rti_text <> ''),
    CONSTRAINT cpio_address_not_empty CHECK (cpio_address <> '')
);

-- Indexes for RTI payload queries
CREATE INDEX idx_rti_contract ON agent_rti_payloads (contract_id);
CREATE INDEX idx_rti_org_generated ON agent_rti_payloads (org_id, generated_at DESC);
CREATE INDEX idx_rti_anomaly_type ON agent_rti_payloads (anomaly_type, anomaly_severity);
CREATE INDEX idx_rti_status ON agent_rti_payloads (status, generated_at DESC);

COMMENT ON TABLE agent_rti_payloads IS 'RTI dossier payloads generated by the rti_generator agent. Immutable legal audit trail.';
COMMENT ON COLUMN agent_rti_payloads.rti_text IS 'Formatted RTI application text ready for printing/sending to CPIO.';

-- ============================================================================
-- TABLE: agent_execution_logs
-- Structured execution logs for agent workflows.
-- Separated from checkpoints for:
--   1. High-volume logging (checkpoints are for state, logs are for events)
--   2. Time-series analysis (execution duration, error rates)
--   3. Debugging and observability
--
-- This table is append-only (no UPDATE/DELETE).
-- ============================================================================

CREATE TABLE agent_execution_logs (
    log_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Temporal workflow identifiers
    workflow_id       TEXT NOT NULL,
    workflow_run_id   TEXT,
    activity_id       TEXT,

    -- Agent identification
    agent_name        TEXT NOT NULL,
    log_level         TEXT NOT NULL DEFAULT 'info',    -- debug | info | warn | error | critical

    -- Log content
    message           TEXT NOT NULL,
    context           JSONB,                           -- Additional structured context

    -- Execution metrics
    execution_duration_ms INTEGER,
    memory_usage_mb   NUMERIC(8, 2),

    -- Traceability
    contract_id       UUID REFERENCES aoc_clean(contract_id) ON DELETE SET NULL,

    -- Timestamp
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT log_message_not_empty CHECK (message <> '')
);

-- Indexes for log queries
CREATE INDEX idx_log_workflow_time ON agent_execution_logs (workflow_id, created_at DESC);
CREATE INDEX idx_log_agent_time ON agent_execution_logs (agent_name, created_at DESC);
CREATE INDEX idx_log_level_time ON agent_execution_logs (log_level, created_at DESC);
CREATE INDEX idx_log_contract ON agent_execution_logs (contract_id, created_at DESC) WHERE contract_id IS NOT NULL;

-- GIN index on context JSONB for structured log queries
CREATE INDEX idx_log_context_gin ON agent_execution_logs USING gin (context jsonb_path_ops);

COMMENT ON TABLE agent_execution_logs IS 'Structured execution logs for agent workflows. Append-only for observability and debugging.';

-- ============================================================================
-- FUNCTIONS: Checkpoint Management
-- ============================================================================

-- Function: Create a new checkpoint
-- Returns the checkpoint_id for reference
CREATE OR REPLACE FUNCTION create_agent_checkpoint(
    p_workflow_id TEXT,
    p_agent_name TEXT,
    p_checkpoint_type checkpoint_type_enum,
    p_state JSONB,
    p_contract_id UUID DEFAULT NULL,
    p_org_id UUID DEFAULT NULL,
    p_vendor_id UUID DEFAULT NULL,
    p_workflow_run_id TEXT DEFAULT NULL,
    p_activity_id TEXT DEFAULT NULL,
    p_execution_duration_ms INTEGER DEFAULT NULL,
    p_expires_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_checkpoint_id UUID;
BEGIN
    INSERT INTO agent_state_checkpoints (
        workflow_id, agent_name, checkpoint_type, state,
        contract_id, org_id, vendor_id,
        workflow_run_id, activity_id,
        execution_duration_ms, expires_at
    ) VALUES (
        p_workflow_id, p_agent_name, p_checkpoint_type, p_state,
        p_contract_id, p_org_id, p_vendor_id,
        p_workflow_run_id, p_activity_id,
        p_execution_duration_ms, p_expires_at
    )
    RETURNING checkpoint_id INTO v_checkpoint_id;

    RETURN v_checkpoint_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION create_agent_checkpoint IS 'Creates a new agent checkpoint. Returns checkpoint_id for reference.';

-- Function: Get latest checkpoint for a workflow + agent
-- Used for workflow resumption (get last known state)
CREATE OR REPLACE FUNCTION get_latest_checkpoint(
    p_workflow_id TEXT,
    p_agent_name TEXT
)
RETURNS TABLE (
    checkpoint_id UUID,
    checkpoint_type checkpoint_type_enum,
    state JSONB,
    created_at TIMESTAMPTZ,
    execution_status TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        c.checkpoint_id,
        c.checkpoint_type,
        c.state,
        c.created_at,
        c.execution_status
    FROM agent_state_checkpoints c
    WHERE c.workflow_id = p_workflow_id
      AND c.agent_name = p_agent_name
    ORDER BY c.created_at DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_latest_checkpoint IS 'Gets the latest checkpoint for a workflow + agent. Used for workflow resumption.';

-- Function: Get all checkpoints for a contract (audit trail)
CREATE OR REPLACE FUNCTION get_contract_checkpoints(p_contract_id UUID)
RETURNS TABLE (
    checkpoint_id UUID,
    agent_name TEXT,
    checkpoint_type checkpoint_type_enum,
    state JSONB,
    execution_status TEXT,
    created_at TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        c.checkpoint_id,
        c.agent_name,
        c.checkpoint_type,
        c.state,
        c.execution_status,
        c.created_at
    FROM agent_state_checkpoints c
    WHERE c.contract_id = p_contract_id
    ORDER BY c.created_at ASC;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_contract_checkpoints IS 'Gets all agent checkpoints related to a specific contract. Used for audit trail and investigation.';

-- Function: Clean up expired checkpoints (TTL cleanup)
-- Should be called periodically via pg_cron
CREATE OR REPLACE FUNCTION cleanup_expired_checkpoints()
RETURNS INTEGER AS $$
DECLARE
    v_deleted_count INTEGER;
BEGIN
    WITH deleted AS (
        DELETE FROM agent_state_checkpoints
        WHERE expires_at IS NOT NULL
          AND expires_at < NOW()
        RETURNING *
    )
    SELECT COUNT(*) INTO v_deleted_count FROM deleted;

    RETURN v_deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION cleanup_expired_checkpoints IS 'Deletes expired checkpoints (TTL cleanup). Call periodically via pg_cron.';

-- ============================================================================
-- TRIGGERS: Auto-update execution_status based on state content
-- ============================================================================

-- Function: Infer execution_status from state JSONB
-- If state contains 'error' key, mark as failed
-- If state contains 'completed' key, mark as completed
CREATE OR REPLACE FUNCTION infer_checkpoint_status()
RETURNS TRIGGER AS $$
BEGIN
    -- Check for error in state
    IF NEW.state ? 'error' THEN
        NEW.execution_status := 'failed';
        NEW.error_message := COALESCE(NEW.state->>'error', 'Unknown error');
    -- Check for completion marker
    ELSIF NEW.state ? 'completed' AND (NEW.state->>'completed')::BOOLEAN = TRUE THEN
        NEW.execution_status := 'completed';
    -- Default to running if not set
    ELSIF NEW.execution_status IS NULL OR NEW.execution_status = '' THEN
        NEW.execution_status := 'running';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_infer_checkpoint_status
    BEFORE INSERT OR UPDATE ON agent_state_checkpoints
    FOR EACH ROW
    EXECUTE FUNCTION infer_checkpoint_status();

-- ============================================================================
-- RETENTION POLICY: Agent memory tables
-- ============================================================================

-- Checkpoints: Keep for 2 years (legal requirement for audit trail)
-- After 2 years, move to cold storage (not implemented in this migration)
CREATE OR REPLACE FUNCTION cleanup_old_checkpoints(retention_interval INTERVAL DEFAULT INTERVAL '2 years')
RETURNS INTEGER AS $$
DECLARE
    v_deleted_count INTEGER;
BEGIN
    WITH deleted AS (
        DELETE FROM agent_state_checkpoints
        WHERE created_at < NOW() - retention_interval
          AND execution_status IN ('completed', 'failed', 'cancelled')
        RETURNING *
    )
    SELECT COUNT(*) INTO v_deleted_count FROM deleted;

    RETURN v_deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION cleanup_old_checkpoints IS 'Deletes old checkpoints beyond retention period. Default: 2 years. Call periodically via pg_cron.';

-- Logs: Keep for 90 days (debugging only, not legal record)
CREATE OR REPLACE FUNCTION cleanup_old_logs(retention_interval INTERVAL DEFAULT INTERVAL '90 days')
RETURNS INTEGER AS $$
DECLARE
    v_deleted_count INTEGER;
BEGIN
    WITH deleted AS (
        DELETE FROM agent_execution_logs
        WHERE created_at < NOW() - retention_interval
        RETURNING *
    )
    SELECT COUNT(*) INTO v_deleted_count FROM deleted;

    RETURN v_deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION cleanup_old_logs IS 'Deletes old execution logs beyond retention period. Default: 90 days. Call periodically via pg_cron.';

-- ============================================================================
-- VIEWS: Agent memory analytics
-- ============================================================================

-- View: Agent execution summary (for monitoring dashboard)
CREATE OR REPLACE VIEW v_agent_execution_summary AS
SELECT
    agent_name,
    checkpoint_type,
    execution_status,
    COUNT(*) AS checkpoint_count,
    AVG(execution_duration_ms) AS avg_duration_ms,
    MAX(execution_duration_ms) AS max_duration_ms,
    MIN(created_at) AS first_seen,
    MAX(created_at) AS last_seen
FROM agent_state_checkpoints
GROUP BY agent_name, checkpoint_type, execution_status;

COMMENT ON VIEW v_agent_execution_summary IS 'Agent execution summary for monitoring dashboard. Shows checkpoint counts, durations, and status distribution.';

-- View: Recent anomalies detected by agents
CREATE OR REPLACE VIEW v_recent_anomalies AS
SELECT
    c.checkpoint_id,
    c.agent_name,
    c.contract_id,
    c.org_id,
    c.vendor_id,
    c.state->>'anomaly_type' AS anomaly_type,
    c.state->>'severity' AS severity,
    c.state->>'description' AS description,
    c.created_at
FROM agent_state_checkpoints c
WHERE c.checkpoint_type = 'episodic'
  AND c.state ? 'anomaly_type'
  AND c.created_at >= NOW() - INTERVAL '7 days'
ORDER BY c.created_at DESC;

COMMENT ON VIEW v_recent_anomalies IS 'Recent anomalies detected by agents in the last 7 days. Powers the real-time anomaly feed on the dashboard.';

-- ============================================================================
-- END OF MIGRATION 004
-- ============================================================================